export default {
  highlight: {
    white: 'hsl(var(--highlight-white))',
    surface: 'hsl(var(--highlight-surface))',
    bg: 'hsl(var(--highlight-bg))',
    hover: 'hsl(var(--highlight-hover))',
    border: 'hsl(var(--highlight-border))',
  },
  primary: {
    DEFAULT: 'hsl(var(--primary-60))',
    15: 'hsl(var(--primary-15))',
    30: 'hsl(var(--primary-30))',
    45: 'hsl(var(--primary-45))',
    60: 'hsl(var(--primary-60))',
    75: 'hsl(var(--primary-75))',
    90: 'hsl(var(--primary-90))',
  },
  secondary: {
    DEFAULT: 'hsl(var(--secondary-60))',
    15: 'hsl(var(--secondary-15))',
    30: 'hsl(var(--secondary-30))',
    45: 'hsl(var(--secondary-45))',
    60: 'hsl(var(--secondary-60))',
    75: 'hsl(var(--secondary-75))',
    90: 'hsl(var(--secondary-90))',
  },
  informative: {
    DEFAULT: 'hsl(var(--informative-60))',
    15: 'hsl(var(--informative-15))',
    30: 'hsl(var(--informative-30))',
    45: 'hsl(var(--informative-45))',
    60: 'hsl(var(--informative-60))',
    75: 'hsl(var(--informative-75))',
    90: 'hsl(var(--informative-90))',
  },
  positive: {
    DEFAULT: 'hsl(var(--positive-60))',
    15: 'hsl(var(--positive-15))',
    30: 'hsl(var(--positive-30))',
    45: 'hsl(var(--positive-45))',
    60: 'hsl(var(--positive-60))',
    75: 'hsl(var(--positive-75))',
    90: 'hsl(var(--positive-90))',
  },
  notice: {
    DEFAULT: 'hsl(var(--notice-60))',
    15: 'hsl(var(--notice-15))',
    30: 'hsl(var(--notice-30))',
    45: 'hsl(var(--notice-45))',
    60: 'hsl(var(--notice-60))',
    75: 'hsl(var(--notice-75))',
    90: 'hsl(var(--notice-90))',
  },
  negative: {
    DEFAULT: 'hsl(var(--negative-60))',
    15: 'hsl(var(--negative-15))',
    30: 'hsl(var(--negative-30))',
    45: 'hsl(var(--negative-45))',
    60: 'hsl(var(--negative-60))',
    75: 'hsl(var(--negative-75))',
    90: 'hsl(var(--negative-90))',
  },
  sidebar: {
    DEFAULT: 'hsl(var(--sidebar-background))',
    accent: 'hsl(var(--sidebar-accent))',
    'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
    border: 'hsl(var(--sidebar-border))',
    ring: 'hsl(var(--sidebar-ring))',
  },
  skeleton: {
    dark: 'hsl(var(--skeleton-dark))',
    light: 'hsl(var(--skeleton-light))',
  },
};
